# File automatically-generated by STM32CubeMX - Do not modify
set(ST_MULTICONTEXT DUAL_CORE CACHE STRING "Type of multi-context")
set(FIRMWARE_VARIANT "TEST" CACHE STRING "Firmware variant to build: TEST or IRON")
set_property(CACHE FIRMWARE_VARIANT PROPERTY STRINGS TEST IRON)

string(TOUPPER "${FIRMWARE_VARIANT}" FIRMWARE_VARIANT)

if(NOT FIRMWARE_VARIANT MATCHES "^(TEST|IRON)$")
    message(FATAL_ERROR "Unsupported FIRMWARE_VARIANT='${FIRMWARE_VARIANT}'. Use TEST or IRON.")
endif()

#-----------------------Build CM4 Project-----------------------#
if((FIRMWARE_VARIANT STREQUAL "TEST") AND (((${BUILD_CONTEXT} MATCHES .*CM4.*) OR (NOT DEFINED BUILD_CONTEXT))))
    message("   Build context: " CM4)
    ExternalProject_Add(nucleotest_CM4
        BINARY_DIR                  ${CMAKE_SOURCE_DIR}/CM4/build
        SOURCE_DIR                  ${PROJECT_SOURCE_DIR}/CM4
        PREFIX                      CM4
        CONFIGURE_HANDLED_BY_BUILD  true
        INSTALL_COMMAND             ""
        CMAKE_ARGS                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        BUILD_ALWAYS                true
    )

	set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/CM4/build")
	set(ST_DUAL_CORE_CM4_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/CM4/build/nucleotest_CM4${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to cm4 project target")
endif()
#-----------------------Build CM7 Project-----------------------#
if((FIRMWARE_VARIANT STREQUAL "TEST") AND (((${BUILD_CONTEXT} MATCHES .*CM7.*) OR (NOT DEFINED BUILD_CONTEXT))))
    message("   Build context: " CM7)
    ExternalProject_Add(nucleotest_CM7
        BINARY_DIR                  ${CMAKE_SOURCE_DIR}/CM7/build
        SOURCE_DIR                  ${PROJECT_SOURCE_DIR}/CM7
        PREFIX                      CM7
        CONFIGURE_HANDLED_BY_BUILD  true
        INSTALL_COMMAND             ""
        CMAKE_ARGS                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        BUILD_ALWAYS                true
    )

	set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/CM7/build")
	set(ST_DUAL_CORE_CM7_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/CM7/build/nucleotest_CM7${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to cm7 project target")
endif()

#-----------------------Build iron CM7 Project-----------------------#
if(FIRMWARE_VARIANT STREQUAL "IRON")
    message("   Build context: " iron_cm7)
    ExternalProject_Add(nucleotest_iron_CM7
        BINARY_DIR                  ${CMAKE_SOURCE_DIR}/iron_cm7/build
        SOURCE_DIR                  ${PROJECT_SOURCE_DIR}/iron_cm7
        PREFIX                      iron_cm7
        CONFIGURE_HANDLED_BY_BUILD  true
        INSTALL_COMMAND             ""
        CMAKE_ARGS                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        BUILD_ALWAYS                true
    )

	set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/iron_cm7/build")
	set(ST_IRON_CM7_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/iron_cm7/build/nucleotest_iron_CM7${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to iron cm7 project target")
endif()

